CREATE TABLE ASSIGNMENT (ID INTEGER AUTO_INCREMENT NOT NULL, ASSIGNEDON DATETIME, DESCRIPTION VARCHAR(255), DUEON DATETIME, TITLE VARCHAR(255), PRIMARY KEY (ID))  engine=InnoDB
CREATE TABLE CLASS (ID INTEGER AUTO_INCREMENT NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID))  engine=InnoDB
CREATE TABLE QUEST (ID INTEGER AUTO_INCREMENT NOT NULL, DESCRIPTION VARCHAR(255), NAME VARCHAR(255), PARENT_ID INTEGER, PRIMARY KEY (ID))  engine=InnoDB
CREATE TABLE QUESTPROGRESS (ID INTEGER AUTO_INCREMENT NOT NULL, COMPLETED TINYINT(1) default 0, UPDATED DATETIME, QUEST_ID INTEGER, TASK_ID INTEGER, USER_ID INTEGER, PRIMARY KEY (ID))  engine=InnoDB
CREATE TABLE TASK (ID INTEGER AUTO_INCREMENT NOT NULL, DESCRIPTION VARCHAR(255), NAME VARCHAR(255), TYPE VARCHAR(255), PARENT_ID INTEGER, QUEST_ID INTEGER, PRIMARY KEY (ID))  engine=InnoDB
CREATE TABLE h_user (ID INTEGER AUTO_INCREMENT NOT NULL, EMAIL VARCHAR(255), FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), PASSWORD VARCHAR(255), STATUS VARCHAR(255), PRIMARY KEY (ID))  engine=InnoDB
CREATE TABLE ENROLLMENT (ID INTEGER AUTO_INCREMENT NOT NULL, TYPE VARCHAR(255), COURSE_ID INTEGER, USER_ID INTEGER, PRIMARY KEY (ID))  engine=InnoDB
ALTER TABLE QUEST ADD CONSTRAINT FK_QUEST_PARENT_ID FOREIGN KEY (PARENT_ID) REFERENCES QUEST (ID)
ALTER TABLE QUESTPROGRESS ADD CONSTRAINT FK_QUESTPROGRESS_TASK_ID FOREIGN KEY (TASK_ID) REFERENCES TASK (ID)
ALTER TABLE QUESTPROGRESS ADD CONSTRAINT FK_QUESTPROGRESS_QUEST_ID FOREIGN KEY (QUEST_ID) REFERENCES QUEST (ID)
ALTER TABLE QUESTPROGRESS ADD CONSTRAINT FK_QUESTPROGRESS_USER_ID FOREIGN KEY (USER_ID) REFERENCES h_user (ID)
ALTER TABLE TASK ADD CONSTRAINT FK_TASK_QUEST_ID FOREIGN KEY (QUEST_ID) REFERENCES QUEST (ID)
ALTER TABLE TASK ADD CONSTRAINT FK_TASK_PARENT_ID FOREIGN KEY (PARENT_ID) REFERENCES TASK (ID)
ALTER TABLE ENROLLMENT ADD CONSTRAINT FK_ENROLLMENT_USER_ID FOREIGN KEY (USER_ID) REFERENCES h_user (ID)
ALTER TABLE ENROLLMENT ADD CONSTRAINT FK_ENROLLMENT_COURSE_ID FOREIGN KEY (COURSE_ID) REFERENCES CLASS (ID)
