
package edu.columbia.cs.psl.halo.server.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CourseServiceService", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", wsdlLocation = "http://amos.cs.columbia.edu:18585/CourseServiceService/CourseService?wsdl")
public class CourseServiceService
    extends Service
{

    private final static URL COURSESERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(edu.columbia.cs.psl.halo.server.stubs.CourseServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = edu.columbia.cs.psl.halo.server.stubs.CourseServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://amos.cs.columbia.edu:18585/CourseServiceService/CourseService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://amos.cs.columbia.edu:18585/CourseServiceService/CourseService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        COURSESERVICESERVICE_WSDL_LOCATION = url;
    }

    public CourseServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CourseServiceService() {
        super(COURSESERVICESERVICE_WSDL_LOCATION, new QName("http://server.halo.psl.cs.columbia.edu/", "CourseServiceService"));
    }

    /**
     * 
     * @return
     *     returns CourseService
     */
    @WebEndpoint(name = "CourseServicePort")
    public CourseService getCourseServicePort() {
        return super.getPort(new QName("http://server.halo.psl.cs.columbia.edu/", "CourseServicePort"), CourseService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CourseService
     */
    @WebEndpoint(name = "CourseServicePort")
    public CourseService getCourseServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.halo.psl.cs.columbia.edu/", "CourseServicePort"), CourseService.class, features);
    }

}
