
package edu.columbia.cs.psl.halo.server.stubs;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CourseService", targetNamespace = "http://server.halo.psl.cs.columbia.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CourseService {


    /**
     * 
     * @param arg0
     * @return
     *     returns edu.columbia.cs.psl.halo.server.stubs.Quest
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createQuest", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.CreateQuest")
    @ResponseWrapper(localName = "createQuestResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.CreateQuestResponse")
    public Quest createQuest(
        @WebParam(name = "arg0", targetNamespace = "")
        Quest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns edu.columbia.cs.psl.halo.server.stubs.Assignment
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAssignment", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.CreateAssignment")
    @ResponseWrapper(localName = "createAssignmentResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.CreateAssignmentResponse")
    public Assignment createAssignment(
        @WebParam(name = "arg0", targetNamespace = "")
        Assignment arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns edu.columbia.cs.psl.halo.server.stubs.Assignment
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateAssignment", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.UpdateAssignment")
    @ResponseWrapper(localName = "updateAssignmentResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.UpdateAssignmentResponse")
    public Assignment updateAssignment(
        @WebParam(name = "arg0", targetNamespace = "")
        Assignment arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns edu.columbia.cs.psl.halo.server.stubs.Quest
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateQuest", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.UpdateQuest")
    @ResponseWrapper(localName = "updateQuestResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.UpdateQuestResponse")
    public Quest updateQuest(
        @WebParam(name = "arg0", targetNamespace = "")
        Quest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteQuest", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.DeleteQuest")
    @ResponseWrapper(localName = "deleteQuestResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.DeleteQuestResponse")
    public boolean deleteQuest(
        @WebParam(name = "arg0", targetNamespace = "")
        Quest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteAssignment", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.DeleteAssignment")
    @ResponseWrapper(localName = "deleteAssignmentResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.DeleteAssignmentResponse")
    public boolean deleteAssignment(
        @WebParam(name = "arg0", targetNamespace = "")
        Assignment arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<edu.columbia.cs.psl.halo.server.stubs.Enrollment>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEnrollmentsForCourse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetEnrollmentsForCourse")
    @ResponseWrapper(localName = "getEnrollmentsForCourseResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetEnrollmentsForCourseResponse")
    public List<Enrollment> getEnrollmentsForCourse(
        @WebParam(name = "arg0", targetNamespace = "")
        Course arg0);

}
