
package edu.columbia.cs.psl.halo.server.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TestServiceService", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", wsdlLocation = "http://lasalle.cs.columbia.edu:8080/TestServiceService/TestService?wsdl")
public class TestServiceService
    extends Service
{

    private final static URL TESTSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(edu.columbia.cs.psl.halo.server.stubs.TestServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = edu.columbia.cs.psl.halo.server.stubs.TestServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://lasalle.cs.columbia.edu:8080/TestServiceService/TestService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://lasalle.cs.columbia.edu:8080/TestServiceService/TestService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TESTSERVICESERVICE_WSDL_LOCATION = url;
    }

    public TestServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestServiceService() {
        super(TESTSERVICESERVICE_WSDL_LOCATION, new QName("http://server.halo.psl.cs.columbia.edu/", "TestServiceService"));
    }

    /**
     * 
     * @return
     *     returns TestService
     */
    @WebEndpoint(name = "TestServicePort")
    public TestService getTestServicePort() {
        return super.getPort(new QName("http://server.halo.psl.cs.columbia.edu/", "TestServicePort"), TestService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestService
     */
    @WebEndpoint(name = "TestServicePort")
    public TestService getTestServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.halo.psl.cs.columbia.edu/", "TestServicePort"), TestService.class, features);
    }

}
