
package edu.columbia.cs.psl.halo.server.stubs;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.1-b01-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://server.halo.psl.cs.columbia.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param arg0
     * @return
     *     returns edu.columbia.cs.psl.halo.server.stubs.Level
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLevel", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetLevel")
    @ResponseWrapper(localName = "getLevelResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetLevelResponse")
    @Action(input = "http://server.halo.psl.cs.columbia.edu/UserService/getLevelRequest", output = "http://server.halo.psl.cs.columbia.edu/UserService/getLevelResponse")
    public Level getLevel(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns edu.columbia.cs.psl.halo.server.stubs.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMe", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetMe")
    @ResponseWrapper(localName = "getMeResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetMeResponse")
    @Action(input = "http://server.halo.psl.cs.columbia.edu/UserService/getMeRequest", output = "http://server.halo.psl.cs.columbia.edu/UserService/getMeResponse")
    public User getMe();

    /**
     * 
     * @return
     *     returns java.util.List<edu.columbia.cs.psl.halo.server.stubs.Enrollment>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEnrollments", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetEnrollments")
    @ResponseWrapper(localName = "getEnrollmentsResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetEnrollmentsResponse")
    @Action(input = "http://server.halo.psl.cs.columbia.edu/UserService/getEnrollmentsRequest", output = "http://server.halo.psl.cs.columbia.edu/UserService/getEnrollmentsResponse")
    public List<Enrollment> getEnrollments();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setDefaultTitle", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.SetDefaultTitle")
    @ResponseWrapper(localName = "setDefaultTitleResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.SetDefaultTitleResponse")
    @Action(input = "http://server.halo.psl.cs.columbia.edu/UserService/setDefaultTitleRequest", output = "http://server.halo.psl.cs.columbia.edu/UserService/setDefaultTitleResponse")
    public boolean setDefaultTitle(
        @WebParam(name = "arg0", targetNamespace = "")
        Title arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Byte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMyProfileImage", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetMyProfileImage")
    @ResponseWrapper(localName = "getMyProfileImageResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetMyProfileImageResponse")
    @Action(input = "http://server.halo.psl.cs.columbia.edu/UserService/getMyProfileImageRequest", output = "http://server.halo.psl.cs.columbia.edu/UserService/getMyProfileImageResponse")
    public List<Byte> getMyProfileImage();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Byte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProfileImage", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetProfileImage")
    @ResponseWrapper(localName = "getProfileImageResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetProfileImageResponse")
    @Action(input = "http://server.halo.psl.cs.columbia.edu/UserService/getProfileImageRequest", output = "http://server.halo.psl.cs.columbia.edu/UserService/getProfileImageResponse")
    public List<Byte> getProfileImage(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setProfileImage", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.SetProfileImage")
    @ResponseWrapper(localName = "setProfileImageResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.SetProfileImageResponse")
    @Action(input = "http://server.halo.psl.cs.columbia.edu/UserService/setProfileImageRequest", output = "http://server.halo.psl.cs.columbia.edu/UserService/setProfileImageResponse")
    public void setProfileImage(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Byte> arg0);

    /**
     * 
     * @return
     *     returns java.util.List<edu.columbia.cs.psl.halo.server.stubs.Achievement>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllAchievements", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetAllAchievements")
    @ResponseWrapper(localName = "getAllAchievementsResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetAllAchievementsResponse")
    @Action(input = "http://server.halo.psl.cs.columbia.edu/UserService/getAllAchievementsRequest", output = "http://server.halo.psl.cs.columbia.edu/UserService/getAllAchievementsResponse")
    public List<Achievement> getAllAchievements();

    /**
     * 
     * @return
     *     returns java.util.List<edu.columbia.cs.psl.halo.server.stubs.Quest>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllQuests", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetAllQuests")
    @ResponseWrapper(localName = "getAllQuestsResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetAllQuestsResponse")
    @Action(input = "http://server.halo.psl.cs.columbia.edu/UserService/getAllQuestsRequest", output = "http://server.halo.psl.cs.columbia.edu/UserService/getAllQuestsResponse")
    public List<Quest> getAllQuests();

    /**
     * 
     * @return
     *     returns java.util.List<edu.columbia.cs.psl.halo.server.stubs.Title>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMyTitles", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetMyTitles")
    @ResponseWrapper(localName = "getMyTitlesResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetMyTitlesResponse")
    @Action(input = "http://server.halo.psl.cs.columbia.edu/UserService/getMyTitlesRequest", output = "http://server.halo.psl.cs.columbia.edu/UserService/getMyTitlesResponse")
    public List<Title> getMyTitles();

    /**
     * 
     * @return
     *     returns java.util.List<edu.columbia.cs.psl.halo.server.stubs.AchievementRecord>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMyAchievements", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetMyAchievements")
    @ResponseWrapper(localName = "getMyAchievementsResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetMyAchievementsResponse")
    @Action(input = "http://server.halo.psl.cs.columbia.edu/UserService/getMyAchievementsRequest", output = "http://server.halo.psl.cs.columbia.edu/UserService/getMyAchievementsResponse")
    public List<AchievementRecord> getMyAchievements();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<edu.columbia.cs.psl.halo.server.stubs.Assignment>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAssignmentsFor", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetAssignmentsFor")
    @ResponseWrapper(localName = "getAssignmentsForResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetAssignmentsForResponse")
    @Action(input = "http://server.halo.psl.cs.columbia.edu/UserService/getAssignmentsForRequest", output = "http://server.halo.psl.cs.columbia.edu/UserService/getAssignmentsForResponse")
    public List<Assignment> getAssignmentsFor(
        @WebParam(name = "arg0", targetNamespace = "")
        Course arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<edu.columbia.cs.psl.halo.server.stubs.Quest>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getQuestsFor", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetQuestsFor")
    @ResponseWrapper(localName = "getQuestsForResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetQuestsForResponse")
    @Action(input = "http://server.halo.psl.cs.columbia.edu/UserService/getQuestsForRequest", output = "http://server.halo.psl.cs.columbia.edu/UserService/getQuestsForResponse")
    public List<Quest> getQuestsFor(
        @WebParam(name = "arg0", targetNamespace = "")
        Assignment arg0);

    /**
     * 
     * @return
     *     returns java.util.List<edu.columbia.cs.psl.halo.server.stubs.QuestProgress>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMyProgress", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetMyProgress")
    @ResponseWrapper(localName = "getMyProgressResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetMyProgressResponse")
    @Action(input = "http://server.halo.psl.cs.columbia.edu/UserService/getMyProgressRequest", output = "http://server.halo.psl.cs.columbia.edu/UserService/getMyProgressResponse")
    public List<QuestProgress> getMyProgress();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRememberMeToken", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetRememberMeToken")
    @ResponseWrapper(localName = "getRememberMeTokenResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetRememberMeTokenResponse")
    @Action(input = "http://server.halo.psl.cs.columbia.edu/UserService/getRememberMeTokenRequest", output = "http://server.halo.psl.cs.columbia.edu/UserService/getRememberMeTokenResponse")
    public String getRememberMeToken();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "markTaskCompleted", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.MarkTaskCompleted")
    @ResponseWrapper(localName = "markTaskCompletedResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.MarkTaskCompletedResponse")
    @Action(input = "http://server.halo.psl.cs.columbia.edu/UserService/markTaskCompletedRequest", output = "http://server.halo.psl.cs.columbia.edu/UserService/markTaskCompletedResponse")
    public void markTaskCompleted(
        @WebParam(name = "arg0", targetNamespace = "")
        Task arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<edu.columbia.cs.psl.halo.server.stubs.QuestProgress>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMyProgressFor", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetMyProgressFor")
    @ResponseWrapper(localName = "getMyProgressForResponse", targetNamespace = "http://server.halo.psl.cs.columbia.edu/", className = "edu.columbia.cs.psl.halo.server.stubs.GetMyProgressForResponse")
    @Action(input = "http://server.halo.psl.cs.columbia.edu/UserService/getMyProgressForRequest", output = "http://server.halo.psl.cs.columbia.edu/UserService/getMyProgressForResponse")
    public List<QuestProgress> getMyProgressFor(
        @WebParam(name = "arg0", targetNamespace = "")
        Quest arg0);

}
